myweb/myweb/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

myweb/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^personal/', include('personal.urls', namespace="personal")),

]

personal/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import login, logout

app_name = "personal"
urlpatterns = [
    url(r'', views.after_login, name='after_login'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.logout, name='log_out'),
    #url(r'^next/$', views.home, name="next"),

]

personal/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User

personal/views.py
from django.core import urlresolvers
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout


def after_login(request):
    return render(request, 'personal/login.html', locals())


def home(request):
    return render(request, 'personal/home.html', locals())


def user_login(request):
    postdata = request.POST.copy()
    username = postdata.get("username", "")
    password = postdata.get("password", "")
    user = authenticate(username=username, password=password)
    if user is not None and user.is_active:
        login(request, user)
        url = urlresolvers.reverse('personal:after_login')
        return HttpResponseRedirect(url)
    else:
        error = "check your username and password!"
        return render(request, 'personal/home.html', locals())


def logout(request):
    logout(request)
    url = urlresolvers.reverse('personal:after_login')
    return HttpResponseRedirect(url)

personal/templates/personal/base.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <meta charset="utf-8">
    <title>{% block title %}base{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'personal/style.css' %}" type="text/css">
    <meta name="viewport" content="width=device-width, initial-scale=1">

<style>
    li{
    display: inline;
    }
</style>
</head>
<body>
<nav class="navbar-fixed-top">
    <ul class="nav nav-pills">
  <li><a href="#home">Home</a></li>
  <li><a href="#news">News</a></li>
  <li><a href="#contact">Contact</a></li>
  <li style="float:right"><a class="active" href="#about">About</a></li>
</ul>
</nav>
<div class="container">
    <h2 style="text-align: center;">Electronic ID Site</h2>
    <p style="text-align: center;">
        get you electronic identification info...
    </p>
</div>
<header>
    <h1>E-id login Login</h1>
    {% if user_login.is_authenticated %}
      Hi {{ user.username }}!
      <a href="{% url 'logout' %}">logout</a>
    {% else %}
      <a href="{% url 'login' %}">login</a>
    {% endif %}
  </header>
  <hr>
{% block content %}

{% endblock %}
  <footer>
  </footer>
</body>
</html>

personal/templates/personal/home.html
{% extends 'personal/base.html' %}

{% block title %}login{% endblock %}

{% block content %}
  <h2>Home</h2>
<form action="{% url ' personal:log_out' %}">
  <button type="submit">Logout</button>
</form>
{% endblock %}

personal/templates/personal/logged_out.html
{% extends 'base.html' %}

{% block title %}See you!{% endblock %}

{% block content %}
  <h2>logged out</h2>
  <p>You have been successfully logged out.</p>
  <p><a href="{% url 'login' %}">log in</a> again.</p>
{% endblock %}

personal/templates/personal/login.html
{% extends 'personal/base.html' %}

{% block title %}login{% endblock %}


{% block content %}
<div id="register_bubble">
 <h2>Welcome</h2>
  <p>You can log in here</p>
  <h2>login</h2>

  <form action="{% url 'personal:login' %}" method="post">
    {% csrf_token %}
      <label name = "username">Username</label>
      <input type = "text">
      <label name = "password">Password</label>
      <input type = "password">
    <button type="submit">Login</button>
  </form>
</div>
<!---

-->
{% endblock %}